language: cpp
script: make COVERAGE=Y
addons:
  coverity_scan:
    project:
      name: "Shulyaka/rtgparser"
      description: "Binary format parser"
    notification_email: shulyaka@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan
env:
  global:
   - secure: "bjrVxQGj4dTVQJUQoZjbtGqAvJSN0F3n9IbKtLpqx/FSS0V305IQCwpQ5z4ICOxtGVYBJ5aJUXgOx/ZAkV1BFnqjw8VKFeW7iGV5cbTrNfnOYkF8VoC7DQKxhkAm9yAoQxnJ0cUrzQBY0sXobA7sX9pJIF+zgC40iZPzFdn3UKEhYiijP4cSLAXn9ouNcl9EVzY4J5e7f1nlzKSp6JZtCMeLfcdLFSRYGLIH43dYTvpmD2Rkv5NQUVoAkEtbkoyQ2iUxujQVUO7VwpXQQyH7GioJyqIDGUzZZ3waGN2ljf6IO7ufly97yEHAmbk+SZvohwxobiIpyeEPpWX1gfTD9szrqDcO/mTVPH/us0P/OjadSSzecmjllbYLDVyfKWhZYqL7TF6ac2VqRiWi53YZMgTIrGIngpqpVBSnnw/7RJvaa8MAgzLTer4ZQ7GLtqCNXodxWoa7itsLcHi4BxUWJLputB6NCDCMoiqf6fn9V0V9PjdLa7/cY7QMKK7CApRFKaBWL31548YfpoKOIzWpTKpuJqYhNEmP6WN7mR0HDYUTegIIJ0HZTWny+xrsJNzXyU6DPWtylAZbiKfJ6s2tPVU5mIN2W2hWZaYuYMYbL5xmm+exRaMy3c3D4Qm9Ktclph6rOrXW7FFoqskZsPol0N6u39umqz4UrTxJiZJYqUs="
before_install:
  - pip install --user cpp-coveralls
after_success:
  - coveralls
