language: cpp
dist: trusty
script: make extratests
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
        coverity_scan:
          project:
            name: "Shulyaka/rtgparser"
            description: "Binary format parser"
          notification_email: shulyaka@gmail.com
          build_command_prepend: "cov-configure --comptype gcc --compiler \"$CXX\" --template && export COVERAGE=N"
          build_command: "make DEBUG=Y"
          branch_pattern: coverity_scan
      env:
        - COMPILER=g++-6
        - secure: "bjrVxQGj4dTVQJUQoZjbtGqAvJSN0F3n9IbKtLpqx/FSS0V305IQCwpQ5z4ICOxtGVYBJ5aJUXgOx/ZAkV1BFnqjw8VKFeW7iGV5cbTrNfnOYkF8VoC7DQKxhkAm9yAoQxnJ0cUrzQBY0sXobA7sX9pJIF+zgC40iZPzFdn3UKEhYiijP4cSLAXn9ouNcl9EVzY4J5e7f1nlzKSp6JZtCMeLfcdLFSRYGLIH43dYTvpmD2Rkv5NQUVoAkEtbkoyQ2iUxujQVUO7VwpXQQyH7GioJyqIDGUzZZ3waGN2ljf6IO7ufly97yEHAmbk+SZvohwxobiIpyeEPpWX1gfTD9szrqDcO/mTVPH/us0P/OjadSSzecmjllbYLDVyfKWhZYqL7TF6ac2VqRiWi53YZMgTIrGIngpqpVBSnnw/7RJvaa8MAgzLTer4ZQ7GLtqCNXodxWoa7itsLcHi4BxUWJLputB6NCDCMoiqf6fn9V0V9PjdLa7/cY7QMKK7CApRFKaBWL31548YfpoKOIzWpTKpuJqYhNEmP6WN7mR0HDYUTegIIJ0HZTWny+xrsJNzXyU6DPWtylAZbiKfJ6s2tPVU5mIN2W2hWZaYuYMYbL5xmm+exRaMy3c3D4Qm9Ktclph6rOrXW7FFoqskZsPol0N6u39umqz4UrTxJiZJYqUs="
        - secure: "UlVx1pPJLeNEPGP8sUo1dwWvo/6Wd3lQ1qIxAiEjq+aZIOgUuu9HQof3h5GSF1fjNO+GPQOxfuGntWqQ1W+jcfdhSeuWM+kHatdiJqR2NxdzLJCQvq7fPyZt1MnJADRfmrhbBgP8j/3IYqJ9HLVIHs0rATly7J3n/hElD74hf7s0KKbUffrI+HQO8vL6mK4pydw9Fh4v9cKpb7lnx7lirhNoOWjVlFP630LORtm2khP+D/Tk+2BHcaluy0rAl57/xMrnm0LIlpwCNSG7INEG2sLygvf9nMzbMNyBHNcxXJylfggVt8shNSK0KUXwXfQ7vBJqJCk+UtFdZK2eJMzuQcj6qESxOtDMViMlnigSoIrI/sNjUbgSSNgryoMietyHgKrDSOZ79iQVW6FuUyvAdzEEt/TkeE3p06qG8KqhRuMvY+U86O/wd7YJG94KSaXM2z0HbU8xXn3dOvEC9YRo1peAYV14HMI4H7vp1bLOK+mpHUBtTw4OqndsaqgbzH1mJ6Hze9aDbvXGrcI1IF1iNa3yLkPAfFkXKhBWzZe8sGx784Jg4rzXJ8q/xar4txr8H8vJuq6yAkyKJkS1JlhVEueko4O5/5oNJE2BtRavD0M/zTDayYecTJ3+MQ7D6HykWYn1bd2kyFcuhhDa/w2T8a22e/iX6ryJxK4vKoMU4pw="
        - COVERAGE=${COVERALLS_REPO_TOKEN:+Y}
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - llvm-3.8-dev
      env:
        - COMPILER=clang++-3.8
env:
  global:
   - CXXFLAGS="$CXXFLAGS${CXXFLAGS:+ }-Werror"
before_install:
  - export CC="$COMPILER"
  - export CXX="$COMPILER"
  - ${CXX} --version
  - test "$COVERAGE" = "Y" && pip install --user cpp-coveralls || echo "Coveralls reporting skipped"
after_success:
  - test "$COVERAGE" = "Y" && coveralls --exclude testparse.cpp --exclude extratests/ --exclude /usr/include/ || echo "Coveralls reporting skipped"
